plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - _cover.md
  - term.md
  - Part.1.overview.md
  - Part.2.library.A.core-concepts.md
  - Part.2.library.B.colors.md
  - Part.2.library.C.gradients.md
  - Part.2.library.D.shadow.md
  - Part.2.library.E.images.md
  - Part.3.drawing.A.shapes.md
  - Part.3.drawing.B.selection.md
  - Part.3.drawing.C.shapes&groups_browser.md
  - Part.3.drawing.D.groups.md
  - Part.3.drawing.E.transforms.md
  - Part.3.drawing.F.Beziers.md
  - Part.3.drawing.G.preview.md
  - Part.3.drawing.H.inspector.md
  - Part.4.canvases&tabs.A.working_with_tabs.md
  - Part.4.canvases&tabs.B.working_with_canvases.md
  - Part.4.canvases&tabs.C.canvas_settings.md
  - Part.5.stylekits&code_generation.A.code_generation.md
  - Part.5.stylekits&code_generation.B.stylekits.md
  - Part.5.stylekits&code_generation.C.resizing_drawing_methods.md
  - Part.5.stylekits&code_generation.D.android.md
  - Part.5.stylekits&code_generation.E.javascript.md
  - Part.6.image_export.md
  - Part.7.variables.A.using_variables.md
  - Part.7.variables.B.expression_language.md
  - Part.8.dynamic_shapes.A.dynamic_shapes.md
  - Part.8.dynamic_shapes.B.resizing_constraints.md
  - Part.8.dynamic_shapes.C.frame&shape_hierachy.md
  - Part.8.dynamic_shapes.D.dynamic_beziers.md
  - Part.8.dynamic_shapes.E.dynamic_shapes&transforms.md
  - Part.9.using_symbols.md

remote_theme: twowei/so-simple-theme

